version: "0008--20-Nov-2022"
copyright: "2022"
author: "Naila"
title: "OS222: Operating Systems 2022-2"
githublink: "https://github.com/nailashfrni/os222"
githubpagelink: "https://nailashfrni.github.io/os222/"
tblink: "https://os.vlsm.org/Log/nailashfrni.tar.bz2.txt"
myloglink: "/TXT/mylog.txt"
encoding: "UTF-8"
github: [metadata]
