version: "0001--10-Sep-2022"
author: "Naila"
title: "OS222: Operating Systems 2022-2"
githublink: "https://github.com/nailashfrni/os222"
githubpagelink: "https://nailashfrni.github.io/os222/"
myloglink: "/TXT/mylog.txt"
encoding: "UTF-8"
github: [metadata]
